name: Build Go binaries

on: push
jobs:
  build-test:
    name: build
    # name: build for ${{ matrix.os }}
    runs-on: macos-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ macos-latest, windows-latest, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # stable: 'false'
          go-version: '1.16'
      - run: go build
